import { db } from "@/lib/db";
import PDFDocument from "pdfkit";

// GET: Generate PDF report for a patient record
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const recordId = searchParams.get("recordId");
  const type = searchParams.get("type") ?? "patient"; // patient | monthly

  if (!recordId && type === "patient") {
    return Response.json({ error: "recordId required for patient report" }, { status: 400 });
  }

  if (type === "patient" && recordId) {
    return generatePatientPDF(recordId);
  }

  const bookId = searchParams.get("bookId");
  if (type === "monthly" && bookId) {
    return generateMonthlyPDF(bookId);
  }

  return Response.json({ error: "Invalid request" }, { status: 400 });
}

async function generatePatientPDF(recordId: string) {
  const record = await db.patientRecord.findUnique({
    where: { id: recordId },
    include: { hospital: true },
  });

  if (!record) {
    return Response.json({ error: "Record not found" }, { status: 404 });
  }

  const patient = record.patient as Record<string, string>;
  const visit = record.visit as Record<string, string>;
  const diagnosis = record.diagnosis as Record<string, unknown>;
  const treatment = record.treatment as { prescriptions: { medication: string; dosage: string; frequency: string; duration: string }[] };
  const aiSummary = record.aiSummary as { brief?: string; clinicalSummary?: string; riskFlags?: string[] } | null;

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Uint8Array[] = [];

  doc.on("data", (chunk: Uint8Array) => chunks.push(chunk));

  const pdfPromise = new Promise<Uint8Array>((resolve) => {
    doc.on("end", () => resolve(new Uint8Array(Buffer.concat(chunks))));
  });

  // Header
  doc.fontSize(18).font("Helvetica-Bold").text(record.hospital.name, { align: "center" });
  if (record.hospital.tagline) {
    doc.fontSize(10).font("Helvetica").text(record.hospital.tagline, { align: "center" });
  }
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#E2E8F0");
  doc.moveDown();

  // Patient Info
  doc.fontSize(14).font("Helvetica-Bold").text("Patient Information");
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  doc.text(`Name: ${patient.fullName ?? "N/A"}`);
  doc.text(`Date of Birth: ${patient.dateOfBirth ?? "N/A"}`);
  doc.text(`Gender: ${patient.gender ?? "N/A"}`);
  doc.text(`Phone: ${patient.phone ?? "N/A"}`);
  doc.text(`Insurance ID: ${patient.insuranceId ?? "N/A"}`);
  doc.moveDown();

  // Visit
  doc.fontSize(14).font("Helvetica-Bold").text("Visit Details");
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  doc.text(`Date: ${visit.date ?? "N/A"}`);
  doc.text(`Chief Complaint: ${visit.chiefComplaint ?? "N/A"}`);
  doc.text(`Department: ${visit.department ?? "N/A"}`);
  doc.moveDown();

  // AI Summary
  if (aiSummary) {
    doc.fontSize(14).font("Helvetica-Bold").text("AI Clinical Summary");
    doc.moveDown(0.5);
    doc.fontSize(10).font("Helvetica");
    doc.text(aiSummary.clinicalSummary ?? "No summary available");
    if (aiSummary.riskFlags && aiSummary.riskFlags.length > 0) {
      doc.moveDown(0.5);
      doc.font("Helvetica-Bold").text("Risk Flags:");
      doc.font("Helvetica");
      aiSummary.riskFlags.forEach((flag) => doc.text(`  - ${flag}`));
    }
    doc.moveDown();
  }

  // Diagnosis
  doc.fontSize(14).font("Helvetica-Bold").text("Diagnosis");
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  doc.text(`Primary: ${(diagnosis.primary as string) ?? "Not recorded"}`);
  if (diagnosis.notes) doc.text(`Notes: ${diagnosis.notes}`);
  doc.moveDown();

  // Treatment
  doc.fontSize(14).font("Helvetica-Bold").text("Treatment & Prescriptions");
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  if (treatment.prescriptions?.length > 0) {
    treatment.prescriptions.forEach((rx, i) => {
      doc.text(`${i + 1}. ${rx.medication} — ${rx.dosage}, ${rx.frequency}, ${rx.duration}`);
    });
  } else {
    doc.text("No prescriptions recorded");
  }
  doc.moveDown(2);

  // Footer
  doc.fontSize(8).fillColor("#94A3B8").text("Generated by NexusLink Health — A Dalxic subsidiary", { align: "center" });

  doc.end();

  const pdfBuffer = await pdfPromise;

  return new Response(pdfBuffer.buffer as ArrayBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="report-${recordId}.pdf"`,
    },
  });
}

async function generateMonthlyPDF(bookId: string) {
  const book = await db.monthlyBook.findUnique({
    where: { id: bookId },
    include: {
      hospital: true,
      patientRecords: { orderBy: { createdAt: "asc" } },
    },
  });

  if (!book) {
    return Response.json({ error: "Book not found" }, { status: 404 });
  }

  const monthNames = ["January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"];

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Uint8Array[] = [];
  doc.on("data", (chunk: Uint8Array) => chunks.push(chunk));
  const pdfPromise = new Promise<Uint8Array>((resolve) => {
    doc.on("end", () => resolve(new Uint8Array(Buffer.concat(chunks))));
  });

  // Cover page
  doc.moveDown(6);
  doc.fontSize(28).font("Helvetica-Bold").text(book.hospital.name, { align: "center" });
  doc.moveDown();
  doc.fontSize(20).font("Helvetica").text(`Monthly Record Book`, { align: "center" });
  doc.fontSize(16).text(`${monthNames[book.month - 1]} ${book.year}`, { align: "center" });
  doc.moveDown(2);
  doc.fontSize(12).text(`Total Patients: ${book.patientRecords.length}`, { align: "center" });
  doc.fontSize(12).text(`Status: ${book.status.toUpperCase()}`, { align: "center" });

  // Patient records
  for (const record of book.patientRecords) {
    doc.addPage();
    const patient = record.patient as Record<string, string>;
    const visit = record.visit as Record<string, string>;
    const diagnosis = record.diagnosis as Record<string, unknown>;

    doc.fontSize(14).font("Helvetica-Bold").text(patient.fullName ?? "Unknown Patient");
    doc.moveDown(0.5);
    doc.fontSize(10).font("Helvetica");
    doc.text(`Visit: ${visit.date ?? "N/A"} | Complaint: ${visit.chiefComplaint ?? "N/A"}`);
    doc.text(`Diagnosis: ${(diagnosis.primary as string) ?? "Not recorded"}`);
    doc.moveDown();
  }

  // Final page — Dalxic branding
  doc.addPage();
  doc.moveDown(8);
  doc.fontSize(12).fillColor("#94A3B8").text("NexusLink Health", { align: "center" });
  doc.fontSize(10).text("A Dalxic subsidiary", { align: "center" });
  doc.moveDown();
  doc.fontSize(8).text("health.dalxic.com", { align: "center" });

  doc.end();
  const pdfBuffer = await pdfPromise;

  return new Response(pdfBuffer.buffer as ArrayBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="book-${book.year}-${book.month}.pdf"`,
    },
  });
}
